packages:
  - "diagrams/aws-lambda-exec-env"
  - "diagrams/aws-lambda-slot-placement"
  - "docs"
  - "benchmarks/perf-v8-event-loop"
  - "benchmarks/perf-v8-event-loop-db"
  - "benchmarks/perf-v8-event-loop-artillery"
  - "benchmarks/perf-v8-event-loop-experiment"
  - "benchmarks/perf-v8-event-loop-results"
  - "pkg/faaasc"
  - "pkg/faaastime"
  - "pkg/primitives/condition"
  - "pkg/primitives/linear"
  - "pkg/primitives/example/task1"
  - "pkg/primitives/example/workflow"
  - "pkg/primitives/example/universe"
  - "pkg/primitives/task"
  - "pkg/runjs"
  - "pkg/utils/faaasman"
  - "pkg/utils/tsconfig"
  - "pkg/utils/universe"
  - "pkg/utils/workflow"
