packages:
  - "diagrams/arch-overview-source"
  - "diagrams/arch-overview-split"
  - "diagrams/aws-faaas-arch"
  - "diagrams/aws-lambda-exec-env"
  - "diagrams/aws-lambda-slot-placement"
  - "diagrams/db-response-times"
  - "diagrams/double-billing-problem"
  - "diagrams/faaas-arch"
  - "diagrams/faaas-message-passing"
  - "diagrams/faaasc-ast-split"
  - "diagrams/pricing"
  - "docs"
  - "benchmarks/faaasc-artillery-mem-results"
  - "benchmarks/faaasc-artillery"
  - "benchmarks/faaasc-adaptive-results"
  - "benchmarks/faaasc-artillery-results"
  - "benchmarks/faaasc-artillery-concat-results"
  - "benchmarks/faaasc-aws-results"
  - "benchmarks/perf-v8-event-loop"
  - "benchmarks/perf-v8-event-loop-db"
  - "benchmarks/perf-v8-event-loop-artillery"
  - "benchmarks/perf-v8-event-loop-experiment"
  - "benchmarks/perf-v8-event-loop-results"
  - "benchmarks/perf-v8-event-loop-results-pprof"
  - "benchmarks/suites/bank"
  - "benchmarks/suites/echoer"
  - "benchmarks/suites/hello-seq"
  - "benchmarks/suites/pets"
  - "benchmarks/suites/warehouse"
  - "pkg/boss-faaas-engine"
  - "pkg/echo-engine"
  - "pkg/faaasc"
  - "pkg/faaastime"
  - "pkg/gateway"
  - "pkg/mq"
  - "pkg/postgres"
  - "pkg/postgres-faaas-engine"
  - "pkg/primitives/condition"
  - "pkg/primitives/linear"
  - "pkg/primitives/example/task1"
  - "pkg/primitives/example/tasks/dec_pet"
  - "pkg/primitives/example/tasks/get_pet"
  - "pkg/primitives/example/tasks/has_permission"
  - "pkg/primitives/example/tasks/inc_pet"
  - "pkg/primitives/example/tasks/parse_auth"
  - "pkg/primitives/example/workflow"
  - "pkg/primitives/example/universe"
  - "pkg/primitives/task"
  - "pkg/runjs"
  - "pkg/storage"
  - "pkg/utils/async"
  - "pkg/utils/aws-adaptor"
  - "pkg/utils/aws-http-adaptor"
  - "pkg/utils/echo"
  - "pkg/utils/faaasman"
  - "pkg/utils/handler"
  - "pkg/utils/resp-estimator"
  - "pkg/utils/resp-monitor"
  - "pkg/utils/sql"
  - "pkg/utils/tsconfig"
  - "pkg/utils/universe"
  - "pkg/utils/workflow"
  - "stack"
