packages:
  - "docs"
  - "benchmarks/perf-v8-event-loop"
  - "benchmarks/perf-v8-event-loop-db"
  - "benchmarks/perf-v8-event-loop-artillery"
  - "benchmarks/perf-v8-event-loop-experiment"
  - "benchmarks/perf-v8-event-loop-results"
