packages:
  - "diagrams/aws-lambda-exec-env"
  - "diagrams/aws-lambda-slot-placement"
  - "docs"
  - "benchmarks/perf-v8-event-loop"
  - "benchmarks/perf-v8-event-loop-db"
  - "benchmarks/perf-v8-event-loop-artillery"
  - "benchmarks/perf-v8-event-loop-experiment"
  - "benchmarks/perf-v8-event-loop-results"
  - "pkg/boss-faaas-engine"
  - "pkg/faaasc"
  - "pkg/faaastime"
  - "pkg/gateway"
  - "pkg/mq"
  - "pkg/postgres"
  - "pkg/postgres-faaas-engine"
  - "pkg/primitives/condition"
  - "pkg/primitives/linear"
  - "pkg/primitives/example/task1"
  - "pkg/primitives/example/tasks/dec_pet"
  - "pkg/primitives/example/tasks/get_pet"
  - "pkg/primitives/example/tasks/has_permission"
  - "pkg/primitives/example/tasks/inc_pet"
  - "pkg/primitives/example/tasks/parse_auth"
  - "pkg/primitives/example/workflow"
  - "pkg/primitives/example/universe"
  - "pkg/primitives/task"
  - "pkg/runjs"
  - "pkg/storage"
  - "pkg/utils/async"
  - "pkg/utils/faaasman"
  - "pkg/utils/tsconfig"
  - "pkg/utils/universe"
  - "pkg/utils/workflow"
