package faaas:linear;

use faaas:task/types;
use faaas:task/callable;

world linear {
    use types.{task-context, task-error};

    import task-fst: func(ctx: task-context) -> result<task-context, task-error>;
    import task-snd: func(ctx: task-context) -> result<task-context, task-error>;

    export callable;
}
