[package]
name = "task"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "component:task"

[package.metadata.component.dependencies]

[dependencies]
wit-bindgen-rt = { version = "0.24.0", features = ["bitflags"] }
