version: "3.9"

x-faas-fn-cfg: &faas-fn-cfg
  init: true
  privileged: true
  build:
    context: .
    dockerfile: benchmarks/perf-v8-event-loop/Dockerfile
  environment:
    BMK_DB_URL: "postgres://${BMK_DB_USER}:${BMK_DB_PASS}@${BMK_DB_HOST}:${BMK_DB_PORT}/${BMK_DB_NAME}"
  cap_add:
    - NET_ADMIN
    - SYS_PTRACE
  deploy:
    resources:
      limits:
        cpus: "0.05"
        memory: 128M
      reservations:
        memory: 128M

services:
  database:
    build:
      context: .
      dockerfile_inline: |
        FROM postgres
        RUN apt-get -y update && apt-get -y install iproute2
    environment:
      POSTGRES_USER: $BMK_DB_USER
      POSTGRES_PASSWORD: $BMK_DB_PASS
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    privileged: true
    cap_add:
      - NET_ADMIN
  migrate:
    build:
      context: .
      dockerfile: benchmarks/perf-v8-event-loop-db/Dockerfile
    restart: on-failure
    depends_on:
      - database
    environment:
      BMK_DB_URL: "postgres://${BMK_DB_USER}:${BMK_DB_PASS}@${BMK_DB_HOST}:${BMK_DB_PORT}/${BMK_DB_NAME}?schema=public"
  on_http_get_pet:
    <<: *faas-fn-cfg
  on_http_get_pets:
    <<: *faas-fn-cfg
  on_http_put_pet:
    <<: *faas-fn-cfg
  on_http_delete_pet:
    <<: *faas-fn-cfg
  artillery:
    build: benchmarks/perf-v8-event-loop-artillery
    privileged: true
    depends_on:
      - database
      - on_http_delete_pet
      - on_http_get_pet
      - on_http_get_pets
      - on_http_put_pet
volumes:
  pgdata:
